[package]
name = "my-counter"
version = "1.0.0"
authors = []

[addresses]
publisher="_"

[dev-addresses]
publisher="0xf2168be2cd7fe303b6acf9c1f1039c0bcdedc8c94587db584667d7a8f344c3de"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
