[package]
name = "my-counter"
version = "1.0.0"
authors = []

[addresses]
publisher="_"

[dev-addresses]
publisher="0xf62391f707fbd748accc3d981ad37133242609c24f2f61e8e220c91bf22c7c19"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
